server:
  servlet:
    application-display-name: map-query
  port: 8081

request:
  baidu:
    host:
      baiduMapBaseUrl: http://api.map.baidu.com
      baiduMapGeocoder: /geocoder/v2/
      baiduMapIPConvert: /location/ip
      baiduMapPlaceSearch: /place/v2/search
      baiduMapGeoConvert: /geoconv/v1/
    ak: Y1XohU4UQoppPo2eRjmdm9ed72qPwKp9
    sk: bsCILEjczffn6Fjfq9SXeyVjh5fGHljh